version: '3.8'

services:
  app:
    build:
      context: .
    platform: linux/amd64
    image: ghcr.io/theo-mrn/exemple:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/Abonnement?schema=public
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    user: "${UID}:${GID}"

  db:
    image: postgres:15-alpine
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Abonnement
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 